/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
    const { nodes, materials } = useGLTF('/models/24-movie-watch-box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} 
    
      scale={[10, 10, 10]}/>
    </group>
  )
}
export default Model;
useGLTF.preload('/models/24-movie-watch-box.glb')